name: CI/CD pipeline for Sms_spam_classification

on:
 
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
  pull_request:
    branches: [ "main" ]
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
    - uses: actions/checkout@v3
      name: Check out code

    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
      image: repo/image
      tags: v1, latest
      registry: registry-url.io
      dockerfile: Dockerfile
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: sms_spam_classifier:latest